FROM n8nio/n8n:latest

ENV GENERIC_TIMEZONE=Asia/Kolkata
ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=admin
ENV N8N_BASIC_AUTH_PASSWORD=admin
ENV DB_TYPE=sqlite
ENV DB_SQLITE_POOL_SIZE=2
ENV N8N_PORT=5678

EXPOSE 5678
CMD ["n8n", "start"]
